### PR TITLE
Change the main executable's name

### PR DESCRIPTION
**Pull request by monacofj**

### CODE REVIEW

**Comment by vpereira13** [comment]
Nice approach!
Don't forget to change the instructions in `README.md` if that [PR](https://github.com/courselab/ttsnake/pull/10) is merged before this.
Or open a issue/tech debit.

**Review by vpereira13 — APPROVED** [review]
Nice approach!
Don't forget to change the instructions in `README.md` if that [PR](https://github.com/courselab/ttsnake/pull/10) is merged before this.
Or open a issue/tech debit.

**Comment by monacofj** [comment]
Suggestion to apply: merge down `develop` into this branch, check/edit `README.md`, and then merge up this branch  into develop.

**Comment by monacofj** [comment]
Long-pending issue.
Solving it.

**Comment by monacofj** [comment]
Long-pending issue. Solving it.

**Pull request merged**
